# Generated by Django 3.2 on 2023-02-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakshy_jol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='number_of_news',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(),
        ),
    ]
