# Generated by Django 3.2 on 2023-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakshy_jol', '0002_auto_20230223_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Нововведения', 'verbose_name_plural': 'Нововведения'},
        ),
        migrations.AlterField(
            model_name='news',
            name='number_of_news',
            field=models.CharField(max_length=120, verbose_name='Номер статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
